export const AGREGAR_PRODUCTOS = 'AGREGAR_PRODUCTOS';
export const AGREGAR_PRODUCTOS_EXITO = 'AGREGAR_PRODUCTOS_EXITO';
export const AGREGAR_PRODUCTOS_ERROR = 'AGREGAR_PRODUCTOS_ERROR';

export const DESCARGA_PRODUCTOS = 'DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const PRODUCTO_ELIMINAR = 'PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINAR_EXITO = 'PRODUCTO_ELIMINAR_EXITO';
export const PRODUCTO_ELIMINAR_ERROR = 'PRODUCTO_ELIMINAR_ERROR';