export const AGREGAR_PRODUCTOS = 'AGREGAR_PRODUCTOS';
export const AGREGAR_PRODUCTOS_EXITO = 'AGREGAR_PRODUCTOS_EXITO';
export const AGREGAR_PRODUCTOS_ERROR = 'AGREGAR_PRODUCTOS_ERROR';

export const DESCARGA_PRODUCTOS = 'DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const PRODUCTO_ELIMINAR = 'PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINAR_EXITO = 'PRODUCTO_ELIMINAR_EXITO';
export const PRODUCTO_ELIMINAR_ERROR = 'PRODUCTO_ELIMINAR_ERROR';

export const PRODUCTO_EDITAR = 'PRODUCTO_EDITAR';

export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO';
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
